services:
  - type: web
    name: printsControl-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    branch: main
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    mounts:
      - type: volume
        name: sqlite-data
        path: /app/data
